apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/istio/istio/manifests/charts/istio-operator/crds/crd-operator.yaml?ref=1.14.1
- github.com/istio/istio/manifests/charts/istio-operator/files/gen-operator.yaml?ref=1.14.1
