apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gateway.yaml
- namespace.yaml
- https://raw.githubusercontent.com/istio/istio/1.14.1/manifests/charts/istio-operator/crds/crd-operator.yaml
- https://raw.githubusercontent.com/istio/istio/1.14.1/manifests/charts/istio-operator/files/gen-operator.yaml
